### ISSUE TITLE
Linux build is failing weirdly

### ISSUE THREAD

**Issue by frol** [conda-forge/kuyruk-feedstock#6]
@jakirkham What is [this error](https://circleci.com/gh/conda-forge/kuyruk-feedstock/13) about?

```
TEST START: kuyruk-7.0.1-py27_0
Error: HTTPError: 409 Client Error: Conflict for url: https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/free/noarch/
```

PR tests passed just fine, but once it is merged, it fails.

**Comment by jakirkham** [comment]
Have seen this before. Think it is just spurious network errors. Did you try restarting? Also we should probably raise this to Continuum's attention.

**Comment by frol** [comment]
Yeah, rebuilding helped, and the build is green now.
